// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/counter/counter.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/counter/counter.service.go -destination=internal/service/mock/counter.service_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	response "github.com/ferriyusra/clean-arch-go-gin/internal/model/response"
	gomock "go.uber.org/mock/gomock"
)

// MockCounterService is a mock of CounterService interface.
type MockCounterService struct {
	ctrl     *gomock.Controller
	recorder *MockCounterServiceMockRecorder
	isgomock struct{}
}

// MockCounterServiceMockRecorder is the mock recorder for MockCounterService.
type MockCounterServiceMockRecorder struct {
	mock *MockCounterService
}

// NewMockCounterService creates a new mock instance.
func NewMockCounterService(ctrl *gomock.Controller) *MockCounterService {
	mock := &MockCounterService{ctrl: ctrl}
	mock.recorder = &MockCounterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterService) EXPECT() *MockCounterServiceMockRecorder {
	return m.recorder
}

// GetCounter mocks base method.
func (m *MockCounterService) GetCounter(ctx context.Context) (*response.GetCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx)
	ret0, _ := ret[0].(*response.GetCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockCounterServiceMockRecorder) GetCounter(ctx any) *MockCounterServiceGetCounterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockCounterService)(nil).GetCounter), ctx)
	return &MockCounterServiceGetCounterCall{Call: call}
}

// MockCounterServiceGetCounterCall wrap *gomock.Call
type MockCounterServiceGetCounterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCounterServiceGetCounterCall) Return(arg0 *response.GetCounter, arg1 error) *MockCounterServiceGetCounterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCounterServiceGetCounterCall) Do(f func(context.Context) (*response.GetCounter, error)) *MockCounterServiceGetCounterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCounterServiceGetCounterCall) DoAndReturn(f func(context.Context) (*response.GetCounter, error)) *MockCounterServiceGetCounterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrementCounter mocks base method.
func (m *MockCounterService) IncrementCounter(ctx context.Context) (*response.GetCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", ctx)
	ret0, _ := ret[0].(*response.GetCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockCounterServiceMockRecorder) IncrementCounter(ctx any) *MockCounterServiceIncrementCounterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockCounterService)(nil).IncrementCounter), ctx)
	return &MockCounterServiceIncrementCounterCall{Call: call}
}

// MockCounterServiceIncrementCounterCall wrap *gomock.Call
type MockCounterServiceIncrementCounterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCounterServiceIncrementCounterCall) Return(arg0 *response.GetCounter, arg1 error) *MockCounterServiceIncrementCounterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCounterServiceIncrementCounterCall) Do(f func(context.Context) (*response.GetCounter, error)) *MockCounterServiceIncrementCounterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCounterServiceIncrementCounterCall) DoAndReturn(f func(context.Context) (*response.GetCounter, error)) *MockCounterServiceIncrementCounterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
