// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/csrf/csrf.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/csrf/csrf.service.go -destination=internal/service/mock/csrf.service_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCSRFService is a mock of CSRFService interface.
type MockCSRFService struct {
	ctrl     *gomock.Controller
	recorder *MockCSRFServiceMockRecorder
	isgomock struct{}
}

// MockCSRFServiceMockRecorder is the mock recorder for MockCSRFService.
type MockCSRFServiceMockRecorder struct {
	mock *MockCSRFService
}

// NewMockCSRFService creates a new mock instance.
func NewMockCSRFService(ctrl *gomock.Controller) *MockCSRFService {
	mock := &MockCSRFService{ctrl: ctrl}
	mock.recorder = &MockCSRFServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCSRFService) EXPECT() *MockCSRFServiceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockCSRFService) GenerateToken() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockCSRFServiceMockRecorder) GenerateToken() *MockCSRFServiceGenerateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockCSRFService)(nil).GenerateToken))
	return &MockCSRFServiceGenerateTokenCall{Call: call}
}

// MockCSRFServiceGenerateTokenCall wrap *gomock.Call
type MockCSRFServiceGenerateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCSRFServiceGenerateTokenCall) Return(arg0 string, arg1 error) *MockCSRFServiceGenerateTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCSRFServiceGenerateTokenCall) Do(f func() (string, error)) *MockCSRFServiceGenerateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCSRFServiceGenerateTokenCall) DoAndReturn(f func() (string, error)) *MockCSRFServiceGenerateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateToken mocks base method.
func (m *MockCSRFService) ValidateToken(token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockCSRFServiceMockRecorder) ValidateToken(token any) *MockCSRFServiceValidateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockCSRFService)(nil).ValidateToken), token)
	return &MockCSRFServiceValidateTokenCall{Call: call}
}

// MockCSRFServiceValidateTokenCall wrap *gomock.Call
type MockCSRFServiceValidateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCSRFServiceValidateTokenCall) Return(arg0 bool) *MockCSRFServiceValidateTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCSRFServiceValidateTokenCall) Do(f func(string) bool) *MockCSRFServiceValidateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCSRFServiceValidateTokenCall) DoAndReturn(f func(string) bool) *MockCSRFServiceValidateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
