// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/health/health.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/health/health.service.go -destination=internal/service/mock/health.service_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	response "github.com/ferriyusra/clean-arch-go-gin/internal/model/response"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthService is a mock of HealthService interface.
type MockHealthService struct {
	ctrl     *gomock.Controller
	recorder *MockHealthServiceMockRecorder
	isgomock struct{}
}

// MockHealthServiceMockRecorder is the mock recorder for MockHealthService.
type MockHealthServiceMockRecorder struct {
	mock *MockHealthService
}

// NewMockHealthService creates a new mock instance.
func NewMockHealthService(ctrl *gomock.Controller) *MockHealthService {
	mock := &MockHealthService{ctrl: ctrl}
	mock.recorder = &MockHealthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthService) EXPECT() *MockHealthServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthService) Check(ctx context.Context) (*response.HealthStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(*response.HealthStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockHealthServiceMockRecorder) Check(ctx any) *MockHealthServiceCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthService)(nil).Check), ctx)
	return &MockHealthServiceCheckCall{Call: call}
}

// MockHealthServiceCheckCall wrap *gomock.Call
type MockHealthServiceCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHealthServiceCheckCall) Return(arg0 *response.HealthStatus, arg1 error) *MockHealthServiceCheckCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHealthServiceCheckCall) Do(f func(context.Context) (*response.HealthStatus, error)) *MockHealthServiceCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHealthServiceCheckCall) DoAndReturn(f func(context.Context) (*response.HealthStatus, error)) *MockHealthServiceCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckWithDependencies mocks base method.
func (m *MockHealthService) CheckWithDependencies(ctx context.Context, checks map[string]func(context.Context) error) (*response.HealthStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWithDependencies", ctx, checks)
	ret0, _ := ret[0].(*response.HealthStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckWithDependencies indicates an expected call of CheckWithDependencies.
func (mr *MockHealthServiceMockRecorder) CheckWithDependencies(ctx, checks any) *MockHealthServiceCheckWithDependenciesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWithDependencies", reflect.TypeOf((*MockHealthService)(nil).CheckWithDependencies), ctx, checks)
	return &MockHealthServiceCheckWithDependenciesCall{Call: call}
}

// MockHealthServiceCheckWithDependenciesCall wrap *gomock.Call
type MockHealthServiceCheckWithDependenciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHealthServiceCheckWithDependenciesCall) Return(arg0 *response.HealthStatus, arg1 error) *MockHealthServiceCheckWithDependenciesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHealthServiceCheckWithDependenciesCall) Do(f func(context.Context, map[string]func(context.Context) error) (*response.HealthStatus, error)) *MockHealthServiceCheckWithDependenciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHealthServiceCheckWithDependenciesCall) DoAndReturn(f func(context.Context, map[string]func(context.Context) error) (*response.HealthStatus, error)) *MockHealthServiceCheckWithDependenciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
