// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/message/message.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/message/message.service.go -destination=internal/service/mock/message.service_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	response "github.com/ferriyusra/clean-arch-go-gin/internal/model/response"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageService is a mock of MessageService interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
	isgomock struct{}
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockMessageService) GetMessage(ctx context.Context) (*response.GetMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx)
	ret0, _ := ret[0].(*response.GetMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMessageServiceMockRecorder) GetMessage(ctx any) *MockMessageServiceGetMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMessageService)(nil).GetMessage), ctx)
	return &MockMessageServiceGetMessageCall{Call: call}
}

// MockMessageServiceGetMessageCall wrap *gomock.Call
type MockMessageServiceGetMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageServiceGetMessageCall) Return(arg0 *response.GetMessage, arg1 error) *MockMessageServiceGetMessageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageServiceGetMessageCall) Do(f func(context.Context) (*response.GetMessage, error)) *MockMessageServiceGetMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageServiceGetMessageCall) DoAndReturn(f func(context.Context) (*response.GetMessage, error)) *MockMessageServiceGetMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
