// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/token/token.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/token/token.service.go -destination=internal/service/mock/token.service_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	token "github.com/ferriyusra/clean-arch-go-gin/internal/service/token"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockTokenService) GenerateAccessToken(userID uuid.UUID, email, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID, email, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenServiceMockRecorder) GenerateAccessToken(userID, email, name any) *MockTokenServiceGenerateAccessTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenService)(nil).GenerateAccessToken), userID, email, name)
	return &MockTokenServiceGenerateAccessTokenCall{Call: call}
}

// MockTokenServiceGenerateAccessTokenCall wrap *gomock.Call
type MockTokenServiceGenerateAccessTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceGenerateAccessTokenCall) Return(arg0 string, arg1 error) *MockTokenServiceGenerateAccessTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceGenerateAccessTokenCall) Do(f func(uuid.UUID, string, string) (string, error)) *MockTokenServiceGenerateAccessTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceGenerateAccessTokenCall) DoAndReturn(f func(uuid.UUID, string, string) (string, error)) *MockTokenServiceGenerateAccessTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GenerateRefreshToken mocks base method.
func (m *MockTokenService) GenerateRefreshToken(userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockTokenServiceMockRecorder) GenerateRefreshToken(userID any) *MockTokenServiceGenerateRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockTokenService)(nil).GenerateRefreshToken), userID)
	return &MockTokenServiceGenerateRefreshTokenCall{Call: call}
}

// MockTokenServiceGenerateRefreshTokenCall wrap *gomock.Call
type MockTokenServiceGenerateRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceGenerateRefreshTokenCall) Return(arg0 string, arg1 error) *MockTokenServiceGenerateRefreshTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceGenerateRefreshTokenCall) Do(f func(uuid.UUID) (string, error)) *MockTokenServiceGenerateRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceGenerateRefreshTokenCall) DoAndReturn(f func(uuid.UUID) (string, error)) *MockTokenServiceGenerateRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateAccessToken mocks base method.
func (m *MockTokenService) ValidateAccessToken(tokenString string) (*token.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenString)
	ret0, _ := ret[0].(*token.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenServiceMockRecorder) ValidateAccessToken(tokenString any) *MockTokenServiceValidateAccessTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenService)(nil).ValidateAccessToken), tokenString)
	return &MockTokenServiceValidateAccessTokenCall{Call: call}
}

// MockTokenServiceValidateAccessTokenCall wrap *gomock.Call
type MockTokenServiceValidateAccessTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceValidateAccessTokenCall) Return(arg0 *token.TokenClaims, arg1 error) *MockTokenServiceValidateAccessTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceValidateAccessTokenCall) Do(f func(string) (*token.TokenClaims, error)) *MockTokenServiceValidateAccessTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceValidateAccessTokenCall) DoAndReturn(f func(string) (*token.TokenClaims, error)) *MockTokenServiceValidateAccessTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateRefreshToken mocks base method.
func (m *MockTokenService) ValidateRefreshToken(tokenString string) (*token.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", tokenString)
	ret0, _ := ret[0].(*token.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockTokenServiceMockRecorder) ValidateRefreshToken(tokenString any) *MockTokenServiceValidateRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockTokenService)(nil).ValidateRefreshToken), tokenString)
	return &MockTokenServiceValidateRefreshTokenCall{Call: call}
}

// MockTokenServiceValidateRefreshTokenCall wrap *gomock.Call
type MockTokenServiceValidateRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceValidateRefreshTokenCall) Return(arg0 *token.TokenClaims, arg1 error) *MockTokenServiceValidateRefreshTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceValidateRefreshTokenCall) Do(f func(string) (*token.TokenClaims, error)) *MockTokenServiceValidateRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceValidateRefreshTokenCall) DoAndReturn(f func(string) (*token.TokenClaims, error)) *MockTokenServiceValidateRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
