// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user/user.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/user/user.service.go -destination=internal/service/mock/user.service_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	request "github.com/ferriyusra/clean-arch-go-gin/internal/model/request"
	response "github.com/ferriyusra/clean-arch-go-gin/internal/model/response"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUserService) ChangePassword(ctx context.Context, userID uuid.UUID, req *request.ChangePasswordRequest) (*response.ChangePasswordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, req)
	ret0, _ := ret[0].(*response.ChangePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserServiceMockRecorder) ChangePassword(ctx, userID, req any) *MockUserServiceChangePasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserService)(nil).ChangePassword), ctx, userID, req)
	return &MockUserServiceChangePasswordCall{Call: call}
}

// MockUserServiceChangePasswordCall wrap *gomock.Call
type MockUserServiceChangePasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceChangePasswordCall) Return(arg0 *response.ChangePasswordResponse, arg1 error) *MockUserServiceChangePasswordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceChangePasswordCall) Do(f func(context.Context, uuid.UUID, *request.ChangePasswordRequest) (*response.ChangePasswordResponse, error)) *MockUserServiceChangePasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceChangePasswordCall) DoAndReturn(f func(context.Context, uuid.UUID, *request.ChangePasswordRequest) (*response.ChangePasswordResponse, error)) *MockUserServiceChangePasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAccount mocks base method.
func (m *MockUserService) DeleteAccount(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockUserServiceMockRecorder) DeleteAccount(ctx, userID any) *MockUserServiceDeleteAccountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockUserService)(nil).DeleteAccount), ctx, userID)
	return &MockUserServiceDeleteAccountCall{Call: call}
}

// MockUserServiceDeleteAccountCall wrap *gomock.Call
type MockUserServiceDeleteAccountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceDeleteAccountCall) Return(arg0 error) *MockUserServiceDeleteAccountCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceDeleteAccountCall) Do(f func(context.Context, uuid.UUID) error) *MockUserServiceDeleteAccountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceDeleteAccountCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockUserServiceDeleteAccountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUser mocks base method.
func (m *MockUserService) GetUser(ctx context.Context, userID string) (*response.GetUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*response.GetUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceMockRecorder) GetUser(ctx, userID any) *MockUserServiceGetUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserService)(nil).GetUser), ctx, userID)
	return &MockUserServiceGetUserCall{Call: call}
}

// MockUserServiceGetUserCall wrap *gomock.Call
type MockUserServiceGetUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceGetUserCall) Return(arg0 *response.GetUser, arg1 error) *MockUserServiceGetUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceGetUserCall) Do(f func(context.Context, string) (*response.GetUser, error)) *MockUserServiceGetUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceGetUserCall) DoAndReturn(f func(context.Context, string) (*response.GetUser, error)) *MockUserServiceGetUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSessions mocks base method.
func (m *MockUserService) ListSessions(ctx context.Context, userID uuid.UUID, currentRefreshToken string, page request.Pagination) (*response.SessionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, userID, currentRefreshToken, page)
	ret0, _ := ret[0].(*response.SessionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockUserServiceMockRecorder) ListSessions(ctx, userID, currentRefreshToken, page any) *MockUserServiceListSessionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockUserService)(nil).ListSessions), ctx, userID, currentRefreshToken, page)
	return &MockUserServiceListSessionsCall{Call: call}
}

// MockUserServiceListSessionsCall wrap *gomock.Call
type MockUserServiceListSessionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceListSessionsCall) Return(arg0 *response.SessionList, arg1 error) *MockUserServiceListSessionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceListSessionsCall) Do(f func(context.Context, uuid.UUID, string, request.Pagination) (*response.SessionList, error)) *MockUserServiceListSessionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceListSessionsCall) DoAndReturn(f func(context.Context, uuid.UUID, string, request.Pagination) (*response.SessionList, error)) *MockUserServiceListSessionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Login mocks base method.
func (m *MockUserService) Login(ctx context.Context, req *request.LoginRequest) (*response.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*response.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceMockRecorder) Login(ctx, req any) *MockUserServiceLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserService)(nil).Login), ctx, req)
	return &MockUserServiceLoginCall{Call: call}
}

// MockUserServiceLoginCall wrap *gomock.Call
type MockUserServiceLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceLoginCall) Return(arg0 *response.LoginResponse, arg1 error) *MockUserServiceLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceLoginCall) Do(f func(context.Context, *request.LoginRequest) (*response.LoginResponse, error)) *MockUserServiceLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceLoginCall) DoAndReturn(f func(context.Context, *request.LoginRequest) (*response.LoginResponse, error)) *MockUserServiceLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PurgeExpiredRefreshTokens mocks base method.
func (m *MockUserService) PurgeExpiredRefreshTokens(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeExpiredRefreshTokens", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeExpiredRefreshTokens indicates an expected call of PurgeExpiredRefreshTokens.
func (mr *MockUserServiceMockRecorder) PurgeExpiredRefreshTokens(ctx any) *MockUserServicePurgeExpiredRefreshTokensCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeExpiredRefreshTokens", reflect.TypeOf((*MockUserService)(nil).PurgeExpiredRefreshTokens), ctx)
	return &MockUserServicePurgeExpiredRefreshTokensCall{Call: call}
}

// MockUserServicePurgeExpiredRefreshTokensCall wrap *gomock.Call
type MockUserServicePurgeExpiredRefreshTokensCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServicePurgeExpiredRefreshTokensCall) Return(arg0 int64, arg1 error) *MockUserServicePurgeExpiredRefreshTokensCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServicePurgeExpiredRefreshTokensCall) Do(f func(context.Context) (int64, error)) *MockUserServicePurgeExpiredRefreshTokensCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServicePurgeExpiredRefreshTokensCall) DoAndReturn(f func(context.Context) (int64, error)) *MockUserServicePurgeExpiredRefreshTokensCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Refresh mocks base method.
func (m *MockUserService) Refresh(ctx context.Context, refreshToken string) (*response.RefreshResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*response.RefreshResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockUserServiceMockRecorder) Refresh(ctx, refreshToken any) *MockUserServiceRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockUserService)(nil).Refresh), ctx, refreshToken)
	return &MockUserServiceRefreshCall{Call: call}
}

// MockUserServiceRefreshCall wrap *gomock.Call
type MockUserServiceRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceRefreshCall) Return(arg0 *response.RefreshResponse, arg1 error) *MockUserServiceRefreshCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceRefreshCall) Do(f func(context.Context, string) (*response.RefreshResponse, error)) *MockUserServiceRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceRefreshCall) DoAndReturn(f func(context.Context, string) (*response.RefreshResponse, error)) *MockUserServiceRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Register mocks base method.
func (m *MockUserService) Register(ctx context.Context, req *request.RegisterUserRequest) (*response.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*response.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceMockRecorder) Register(ctx, req any) *MockUserServiceRegisterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserService)(nil).Register), ctx, req)
	return &MockUserServiceRegisterCall{Call: call}
}

// MockUserServiceRegisterCall wrap *gomock.Call
type MockUserServiceRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceRegisterCall) Return(arg0 *response.RegisterResponse, arg1 error) *MockUserServiceRegisterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceRegisterCall) Do(f func(context.Context, *request.RegisterUserRequest) (*response.RegisterResponse, error)) *MockUserServiceRegisterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceRegisterCall) DoAndReturn(f func(context.Context, *request.RegisterUserRequest) (*response.RegisterResponse, error)) *MockUserServiceRegisterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeRefreshTokens mocks base method.
func (m *MockUserService) RevokeRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshTokens indicates an expected call of RevokeRefreshTokens.
func (mr *MockUserServiceMockRecorder) RevokeRefreshTokens(ctx, userID any) *MockUserServiceRevokeRefreshTokensCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshTokens", reflect.TypeOf((*MockUserService)(nil).RevokeRefreshTokens), ctx, userID)
	return &MockUserServiceRevokeRefreshTokensCall{Call: call}
}

// MockUserServiceRevokeRefreshTokensCall wrap *gomock.Call
type MockUserServiceRevokeRefreshTokensCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceRevokeRefreshTokensCall) Return(arg0 error) *MockUserServiceRevokeRefreshTokensCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceRevokeRefreshTokensCall) Do(f func(context.Context, uuid.UUID) error) *MockUserServiceRevokeRefreshTokensCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceRevokeRefreshTokensCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockUserServiceRevokeRefreshTokensCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StoreRefreshToken mocks base method.
func (m *MockUserService) StoreRefreshToken(ctx context.Context, userID uuid.UUID, tokenStr string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshToken", ctx, userID, tokenStr, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshToken indicates an expected call of StoreRefreshToken.
func (mr *MockUserServiceMockRecorder) StoreRefreshToken(ctx, userID, tokenStr, expiresAt any) *MockUserServiceStoreRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshToken", reflect.TypeOf((*MockUserService)(nil).StoreRefreshToken), ctx, userID, tokenStr, expiresAt)
	return &MockUserServiceStoreRefreshTokenCall{Call: call}
}

// MockUserServiceStoreRefreshTokenCall wrap *gomock.Call
type MockUserServiceStoreRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceStoreRefreshTokenCall) Return(arg0 error) *MockUserServiceStoreRefreshTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceStoreRefreshTokenCall) Do(f func(context.Context, uuid.UUID, string, time.Time) error) *MockUserServiceStoreRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceStoreRefreshTokenCall) DoAndReturn(f func(context.Context, uuid.UUID, string, time.Time) error) *MockUserServiceStoreRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
