// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/counter.repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/counter.repository_interface.go -destination=internal/repository/mock/counter.repository_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCounterRepository is a mock of CounterRepository interface.
type MockCounterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCounterRepositoryMockRecorder
	isgomock struct{}
}

// MockCounterRepositoryMockRecorder is the mock recorder for MockCounterRepository.
type MockCounterRepositoryMockRecorder struct {
	mock *MockCounterRepository
}

// NewMockCounterRepository creates a new mock instance.
func NewMockCounterRepository(ctrl *gomock.Controller) *MockCounterRepository {
	mock := &MockCounterRepository{ctrl: ctrl}
	mock.recorder = &MockCounterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterRepository) EXPECT() *MockCounterRepositoryMockRecorder {
	return m.recorder
}

// GetCounter mocks base method.
func (m *MockCounterRepository) GetCounter(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockCounterRepositoryMockRecorder) GetCounter(ctx any) *MockCounterRepositoryGetCounterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockCounterRepository)(nil).GetCounter), ctx)
	return &MockCounterRepositoryGetCounterCall{Call: call}
}

// MockCounterRepositoryGetCounterCall wrap *gomock.Call
type MockCounterRepositoryGetCounterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCounterRepositoryGetCounterCall) Return(arg0 int, arg1 error) *MockCounterRepositoryGetCounterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCounterRepositoryGetCounterCall) Do(f func(context.Context) (int, error)) *MockCounterRepositoryGetCounterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCounterRepositoryGetCounterCall) DoAndReturn(f func(context.Context) (int, error)) *MockCounterRepositoryGetCounterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrementCounter mocks base method.
func (m *MockCounterRepository) IncrementCounter(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockCounterRepositoryMockRecorder) IncrementCounter(ctx any) *MockCounterRepositoryIncrementCounterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockCounterRepository)(nil).IncrementCounter), ctx)
	return &MockCounterRepositoryIncrementCounterCall{Call: call}
}

// MockCounterRepositoryIncrementCounterCall wrap *gomock.Call
type MockCounterRepositoryIncrementCounterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCounterRepositoryIncrementCounterCall) Return(arg0 int, arg1 error) *MockCounterRepositoryIncrementCounterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCounterRepositoryIncrementCounterCall) Do(f func(context.Context) (int, error)) *MockCounterRepositoryIncrementCounterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCounterRepositoryIncrementCounterCall) DoAndReturn(f func(context.Context) (int, error)) *MockCounterRepositoryIncrementCounterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
