// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/message.repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/message.repository_interface.go -destination=internal/repository/mock/message.repository_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockMessageRepository) GetMessage(ctx context.Context, key string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, key)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMessageRepositoryMockRecorder) GetMessage(ctx, key any) *MockMessageRepositoryGetMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMessageRepository)(nil).GetMessage), ctx, key)
	return &MockMessageRepositoryGetMessageCall{Call: call}
}

// MockMessageRepositoryGetMessageCall wrap *gomock.Call
type MockMessageRepositoryGetMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageRepositoryGetMessageCall) Return(arg0 *string, arg1 error) *MockMessageRepositoryGetMessageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageRepositoryGetMessageCall) Do(f func(context.Context, string) (*string, error)) *MockMessageRepositoryGetMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageRepositoryGetMessageCall) DoAndReturn(f func(context.Context, string) (*string, error)) *MockMessageRepositoryGetMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
