// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/refresh_token.repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/refresh_token.repository_interface.go -destination=internal/repository/mock/refresh_token.repository_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/ferriyusra/clean-arch-go-gin/internal/model/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, token entity.RefreshTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, token any) *MockRefreshTokenRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, token)
	return &MockRefreshTokenRepositoryCreateCall{Call: call}
}

// MockRefreshTokenRepositoryCreateCall wrap *gomock.Call
type MockRefreshTokenRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryCreateCall) Return(arg0 error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryCreateCall) Do(f func(context.Context, entity.RefreshTokenEntity) error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryCreateCall) DoAndReturn(f func(context.Context, entity.RefreshTokenEntity) error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByTokenHash mocks base method.
func (m *MockRefreshTokenRepository) DeleteByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTokenHash indicates an expected call of DeleteByTokenHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteByTokenHash(ctx, tokenHash any) *MockRefreshTokenRepositoryDeleteByTokenHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTokenHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteByTokenHash), ctx, tokenHash)
	return &MockRefreshTokenRepositoryDeleteByTokenHashCall{Call: call}
}

// MockRefreshTokenRepositoryDeleteByTokenHashCall wrap *gomock.Call
type MockRefreshTokenRepositoryDeleteByTokenHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryDeleteByTokenHashCall) Return(arg0 error) *MockRefreshTokenRepositoryDeleteByTokenHashCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryDeleteByTokenHashCall) Do(f func(context.Context, string) error) *MockRefreshTokenRepositoryDeleteByTokenHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryDeleteByTokenHashCall) DoAndReturn(f func(context.Context, string) error) *MockRefreshTokenRepositoryDeleteByTokenHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByUserID mocks base method.
func (m *MockRefreshTokenRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteByUserID), ctx, userID)
	return &MockRefreshTokenRepositoryDeleteByUserIDCall{Call: call}
}

// MockRefreshTokenRepositoryDeleteByUserIDCall wrap *gomock.Call
type MockRefreshTokenRepositoryDeleteByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryDeleteByUserIDCall) Return(arg0 error) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryDeleteByUserIDCall) Do(f func(context.Context, uuid.UUID) error) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryDeleteByUserIDCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteExpired mocks base method.
func (m *MockRefreshTokenRepository) DeleteExpired(ctx context.Context, before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteExpired(ctx, before any) *MockRefreshTokenRepositoryDeleteExpiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteExpired), ctx, before)
	return &MockRefreshTokenRepositoryDeleteExpiredCall{Call: call}
}

// MockRefreshTokenRepositoryDeleteExpiredCall wrap *gomock.Call
type MockRefreshTokenRepositoryDeleteExpiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryDeleteExpiredCall) Return(arg0 int64, arg1 error) *MockRefreshTokenRepositoryDeleteExpiredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryDeleteExpiredCall) Do(f func(context.Context, time.Time) (int64, error)) *MockRefreshTokenRepositoryDeleteExpiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryDeleteExpiredCall) DoAndReturn(f func(context.Context, time.Time) (int64, error)) *MockRefreshTokenRepositoryDeleteExpiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByTokenHash mocks base method.
func (m *MockRefreshTokenRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*entity.RefreshTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.RefreshTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindByTokenHash(ctx, tokenHash any) *MockRefreshTokenRepositoryFindByTokenHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindByTokenHash), ctx, tokenHash)
	return &MockRefreshTokenRepositoryFindByTokenHashCall{Call: call}
}

// MockRefreshTokenRepositoryFindByTokenHashCall wrap *gomock.Call
type MockRefreshTokenRepositoryFindByTokenHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryFindByTokenHashCall) Return(arg0 *entity.RefreshTokenEntity, arg1 error) *MockRefreshTokenRepositoryFindByTokenHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryFindByTokenHashCall) Do(f func(context.Context, string) (*entity.RefreshTokenEntity, error)) *MockRefreshTokenRepositoryFindByTokenHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryFindByTokenHashCall) DoAndReturn(f func(context.Context, string) (*entity.RefreshTokenEntity, error)) *MockRefreshTokenRepositoryFindByTokenHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
