// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/refresh_token.repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/refresh_token.repository_interface.go -destination=internal/repository/mock/refresh_token.repository_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/ferriyusra/clean-arch-go-gin/internal/model/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, token entity.RefreshTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, token any) *MockRefreshTokenRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, token)
	return &MockRefreshTokenRepositoryCreateCall{Call: call}
}

// MockRefreshTokenRepositoryCreateCall wrap *gomock.Call
type MockRefreshTokenRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryCreateCall) Return(arg0 error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryCreateCall) Do(f func(context.Context, entity.RefreshTokenEntity) error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryCreateCall) DoAndReturn(f func(context.Context, entity.RefreshTokenEntity) error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByToken mocks base method.
func (m *MockRefreshTokenRepository) DeleteByToken(ctx context.Context, tokenString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByToken", ctx, tokenString)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByToken indicates an expected call of DeleteByToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteByToken(ctx, tokenString any) *MockRefreshTokenRepositoryDeleteByTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteByToken), ctx, tokenString)
	return &MockRefreshTokenRepositoryDeleteByTokenCall{Call: call}
}

// MockRefreshTokenRepositoryDeleteByTokenCall wrap *gomock.Call
type MockRefreshTokenRepositoryDeleteByTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryDeleteByTokenCall) Return(arg0 error) *MockRefreshTokenRepositoryDeleteByTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryDeleteByTokenCall) Do(f func(context.Context, string) error) *MockRefreshTokenRepositoryDeleteByTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryDeleteByTokenCall) DoAndReturn(f func(context.Context, string) error) *MockRefreshTokenRepositoryDeleteByTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByUserID mocks base method.
func (m *MockRefreshTokenRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteByUserID), ctx, userID)
	return &MockRefreshTokenRepositoryDeleteByUserIDCall{Call: call}
}

// MockRefreshTokenRepositoryDeleteByUserIDCall wrap *gomock.Call
type MockRefreshTokenRepositoryDeleteByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryDeleteByUserIDCall) Return(arg0 error) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryDeleteByUserIDCall) Do(f func(context.Context, uuid.UUID) error) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryDeleteByUserIDCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockRefreshTokenRepositoryDeleteByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByToken mocks base method.
func (m *MockRefreshTokenRepository) FindByToken(ctx context.Context, tokenString string) (*entity.RefreshTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, tokenString)
	ret0, _ := ret[0].(*entity.RefreshTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindByToken(ctx, tokenString any) *MockRefreshTokenRepositoryFindByTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindByToken), ctx, tokenString)
	return &MockRefreshTokenRepositoryFindByTokenCall{Call: call}
}

// MockRefreshTokenRepositoryFindByTokenCall wrap *gomock.Call
type MockRefreshTokenRepositoryFindByTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryFindByTokenCall) Return(arg0 *entity.RefreshTokenEntity, arg1 error) *MockRefreshTokenRepositoryFindByTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryFindByTokenCall) Do(f func(context.Context, string) (*entity.RefreshTokenEntity, error)) *MockRefreshTokenRepositoryFindByTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryFindByTokenCall) DoAndReturn(f func(context.Context, string) (*entity.RefreshTokenEntity, error)) *MockRefreshTokenRepositoryFindByTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
