// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/tx.repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/tx.repository_interface.go -destination=internal/repository/mock/tx.repository_mock.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithinTx mocks base method.
func (m *MockTxManager) WithinTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTx indicates an expected call of WithinTx.
func (mr *MockTxManagerMockRecorder) WithinTx(ctx, fn any) *MockTxManagerWithinTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTx", reflect.TypeOf((*MockTxManager)(nil).WithinTx), ctx, fn)
	return &MockTxManagerWithinTxCall{Call: call}
}

// MockTxManagerWithinTxCall wrap *gomock.Call
type MockTxManagerWithinTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTxManagerWithinTxCall) Return(arg0 error) *MockTxManagerWithinTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTxManagerWithinTxCall) Do(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTxManagerWithinTxCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
